OSM_DB="osm_planet_full_1_1"
HIGHWAY_COUNT_QUERY="insert into stats.highwaycounts values (now(), (select hstore(array_agg(t::text),array_agg(c::text)) from (select tags->'highway' as t, count(1) as c from ways where tags?'highway' and (linestring && Box2d(st_geomfromtext('linestring(-124.7625 24.5210, -66.9326 49.3845)')) or linestring && Box2d(st_geomfromtext('linestring(-179.1506 51.2097, -129.9795 71.4410)')) or linestring && Box2d(st_geomfromtext('linestring(-160.2471 18.9117, -154.8066 22.2356)'))) group by tags->'highway') foo));"
HIGHWAY_LENGTH_QUERY="insert into stats.highwaylengths values (now(), (select hstore(array_agg(t::text),array_agg(c::text)) from (select tags->'highway' as t, sum(st_length(st_transform(linestring, 3786))) as c from ways where tags?'highway' and (linestring && Box2d(st_geomfromtext('linestring(-124.7625 24.5210, -66.9326 49.3845)')) or linestring && Box2d(st_geomfromtext('linestring(-179.1506 51.2097, -129.9795 71.4410)')) or linestring && Box2d(st_geomfromtext('linestring(-160.2471 18.9117, -154.8066 22.2356)'))) group by tags->'highway') foo));"
RELATION_COUNT_QUERY="insert into stats.relationcounts values (now(), (select hstore(array_agg(t::text),array_agg(c::text)) from (select tags->'network' t, count(1) c from relations where tags->'type' = 'route' and tags->'route' = 'road' and tags?'network' group by tags->'network') foo));"
echo "----------------------------------------------------------"
echo "start: `date`"
psql -U postgres -d $OSM_DB -c "$HIGHWAY_COUNT_QUERY"
psql -U postgres -d $OSM_DB -c "$HIGHWAY_LENGTH_QUERY"
psql -U postgres -d $OSM_DB -c "$RELATION_COUNT_QUERY"
echo "end: `date`"
echo "----------------------------------------------------------"
